In [1]:
y="Number of the participants:25"
sub("25","30",y)

[1] "Number of the participants:30"

In [5]:
y="Mr.singh is the smart one. MR. singh is funny,too"
y

[1] "Mr.singh is the smart one. MR. singh is funny,too"

In [7]:
sub("Mr.singh","Professor jha",y)

[1] "Professor jha is the smart one. MR. singh is funny,too"

In [9]:
gsub("Mr.singh","Professor Jha",y)

[1] "Professor Jha is the smart one. MR. singh is funny,too"

In [10]:
str=c("R course","exercise","include example of R language")

In [13]:
grep("ex", str)

[1] 2 3

In [14]:
grep("ex", str, value = TRUE)

[1] "exercise"                      "include example of R language"

In [15]:
str=c("R course","exercises","include examples of r language","in R software")
grep("R",str,ignore.case=F,value=T)

[1] "R course"      "in R software"

In [16]:
grep("R",str,ignore.case=T,value=T)

[1] "R course"                       "exercises"
[3] "include examples of r language" "in R software"

In [17]:
grep("R",str,ignore.case=T,value=F)

[1] 1 2 3 4

In [19]:
grep("R",str,ignore.case=F,value=F)

[1] 1 4

In [22]:
x="R course 24.07.2021"
y="Number of participants:25"
c(x,y)
grep("our",c(x,y))

[1] "R course 24.07.2021"       "Number of participants:25"

[1] 1

In [23]:
x="R course 24.07.2022"
y="Number of participants:50"
c(x,y)

[1] "R course 24.07.2022"       "Number of participants:50"

In [24]:
grep("Num",c(x,y))

[1] 2

In [27]:
str=c("R Course","exercise","Include examples of R language")
grepl("R",str)

[1]  TRUE FALSE  TRUE

In [29]:
grepl("ex",str)

[1] FALSE  TRUE  TRUE

In [33]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

In [34]:
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

In [35]:
is.numeric(painters$School)

[1] FALSE

In [36]:
is.numeric(painters$Drawing)

[1] TRUE

In [38]:
is.factor(painters$School)

[1] TRUE

In [39]:
is.factor(painters$Drawing)

[1] FALSE

In [40]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

In [41]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

In [42]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [43]:
attach(painters)

In [44]:
summary(School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [45]:
summary(Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

In [46]:
detach(painters)

In [47]:
summary(School)

ERROR: Error: object 'School' not found

In [49]:
subset(painters,School=='F')

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [50]:
painters[painters[["School"]]=="F",]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [51]:
subset(painters,Composition<=6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

In [52]:
subset(painters,School=="F",select=c(-3,-5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

In [53]:
splitted=split(painters,painters$School)

In [54]:
splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

In [55]:
is.data.frame(splitted$A)

[1] TRUE

In [56]:
df1=data.frame(state=c("UP","MP","AP","JK"),
                       popnsize=c(1000,2000,3000,4000))

In [57]:
df2=data.frame(state=c("UP","MP","AP","JK"),
                       popnsize=c(100,200,300,400))

In [58]:
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [59]:
df2

  state popnsize
1 UP    100
2 MP    200
3 AP    300
4 JK    400

In [60]:
cbind(df1,df2)

  state popnsize state popnsize
1 UP    1000     UP    100
2 MP    2000     MP    200
3 AP    3000     AP    300
4 JK    4000     JK    400

In [63]:
surveycompleted=c("Yes","No","Yes","No")

In [64]:
merge(df1,df2,by="state")

  state popnsize.x popnsize.y
1 AP    3000       300
2 JK    4000       400
3 MP    2000       200
4 UP    1000       100

In [65]:
df11=data.frame(state=c("UP","MP","AP","JK"),popnsize=c(1000,2000,3000,4000))

In [67]:
df22=data.frame(state=c("bihar","Delhi","Punjab"),popnsize=c(100,200,300))

In [68]:
df11

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [69]:
df22

  state  popnsize
1 bihar  100
2 Delhi  200
3 Punjab 300

In [70]:
rbind(df11,df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 bihar   100
6 Delhi   200
7 Punjab  300