In [1]:
cat("The zero occurs at",2*pi,"radians")

The zero occurs at 6.283185 radians

In [2]:
d=date()
cat("today's date is:",d,"\n")

today's date is: Wed Sep 23 04:05:53 2026

In [3]:
x=1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [5]:
cat(x,sep=" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [6]:
cat(x,sep=" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [7]:
x=7
cat("The square of ",x,"is",x^2,"!\n")

The square of  7 is 49 !

In [8]:
cat("The square root of",x,"is approximately",format(sqrt(x),digit=3),"\n")

The square root of 7 is approximately 2.65

In [9]:
evenno=c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [10]:
cat("the first few even numbers are:",evenno,"..\n")

the first few even numbers are: 2 4 6 8 10 ..

In [11]:
x=1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [12]:
cat(x,fill=2,labels=paste("(",letters[1:10],"):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [13]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [14]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [15]:
paste("everybody","loves","R programming")

[1] "everybody loves R programming"

In [16]:
paste("everybody","Loves","R programming",sep="*")

[1] "everybody*Loves*R programming"

In [17]:
paste("Everybody","loves","R programming", sep="===")

[1] "Everybody===loves===R programming"

In [19]:
names=c("Prof.Singh","Mr. venkat","Dr. Jha")
names

[1] "Prof.Singh" "Mr. venkat" "Dr. Jha"

In [26]:
paste(names,"is","a good","person")

[1] "Prof.Singh is a good person" "Mr. venkat is a good person"
[3] "Dr. Jha is a good person"

In [28]:
paste(names,"is","a good","person",collapse=", and ")

[1] "Prof.Singh is a good person, and Mr. venkat is a good person, and Dr. Jha is a good person"

In [31]:
paste(1," is first    ",2," is second     ",3," is third",sep="#")

[1] "1# is first    #2# is second     #3# is third"

In [32]:
x=paste("ex",1:5,sep="_")
x

[1] "ex_1" "ex_2" "ex_3" "ex_4" "ex_5"

In [34]:
x=paste("Ex",1:5,sep="_",collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [35]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [36]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [37]:
paste0(1:10,c("st","nd","rp",rep("th",7)))

 [1] "1st"  "2nd"  "3rp"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [38]:
paste(1:10,c("st","nd","rd",rep("th",7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [40]:
x="The&!syntax&!of&!paste&!is!&available!&inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [41]:
strsplit(x,split="!")

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

In [42]:
strsplit(x,split="&!")

[[1]]
[1] "The"                              "syntax"
[3] "of"                               "paste"
[5] "is!&available!&inthe online-help"

In [44]:
y=strsplit(x,split="!&")
y

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

In [46]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [47]:
y[[1]][2]

[1] "available"

In [48]:
y[[1]][3]

[1] "inthe online-help"

In [50]:
dates=c("2020-07-24","2021-08-25","2022-09-26","2023-10-27")
datesplit=strsplit(dates,"-")
datesplit

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [54]:
datemat=matrix(unlist(datesplit),nrow=4,ncol=3,byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [55]:
datematrix=matrix(as.numeric(unlist(datesplit)),nrow=4,ncol=3,byrow=TRUE)

In [56]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [57]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [60]:
nchar(x,type="chars",allowNA=FALSE,keepNA=NA)
nzchar(x,keepNA=FALSE)

[1] 56

[1] TRUE

In [62]:
x="R course 24.07.2022"
y="Number of participants:25"
nchar(x)
nchar(y)

[1] 19

[1] 25

In [63]:
nzchar(x)

[1] TRUE

In [64]:
nzchar(y)

[1] TRUE

In [65]:
x=c("Apple","Banana","Cake")
x

[1] "Apple"  "Banana" "Cake"

In [67]:
y=c("Apple","banana","")
y

[1] "Apple"  "banana" ""

In [69]:
nzchar(y)

[1]  TRUE  TRUE FALSE

In [70]:
x=c("Apple","Banana","Cake")
nchar(x)

[1] 5 6 4

In [71]:
y=c(2,4,6)
nchar(y)

[1] 1 1 1

In [72]:
z=c(11,222,3333)
nzchar(z)

[1] TRUE TRUE TRUE

In [73]:
z1=c(1.1,2.22,3.333)
nchar(z1)

[1] 3 4 5

In [74]:
x="R course will start from 24.07.2022"
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [75]:
z="IIT"
tolower(z)

[1] "iit"